# Generated by Django 5.2.10 on 2026-02-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('candidate_name', models.CharField(default='Trial Candidate', max_length=255)),
                ('call_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('local_recording_path', models.CharField(blank=True, max_length=512, null=True)),
                ('technical_score', models.IntegerField(blank=True, null=True)),
                ('communication_score', models.IntegerField(blank=True, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('transcript_summary', models.TextField(blank=True, null=True)),
                ('full_report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
