# Generated by Django 5.2.10 on 2026-02-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='ice_breaker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_role',
            field=models.CharField(default='Software Engineer', max_length=255),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='num_questions',
            field=models.IntegerField(default=2),
        ),
    ]
