# Generated by Django 5.2.10 on 2026-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0002_interviewsession_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='mandatory_requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
